#!/usr/bin/env bash
# Write the deployment's Terraform variables for a CI run from TF_VAR_* environment
# variables (GitHub Actions variables and one secret), skipping any that are unset so an
# empty string never reaches a validated variable. alert_email is required.
# Usage: scripts/ci_tfvars.sh infra/envs/dev/ci.auto.tfvars
set -euo pipefail

OUT="${1:?usage: ci_tfvars.sh <path/to/ci.auto.tfvars>}"

if [ -z "${TF_VAR_alert_email:-}" ]; then
  echo "TF_VAR_alert_email is not set: add the TF_VAR_ALERT_EMAIL repository secret (make ci-config)" >&2
  exit 1
fi

{
  echo "# generated by scripts/ci_tfvars.sh for this CI run; git-ignored"
  echo "alert_email = \"${TF_VAR_alert_email}\""
  [ -n "${TF_VAR_provider_name:-}" ] && echo "provider_name = \"${TF_VAR_provider_name}\""
  [ -n "${TF_VAR_owner:-}" ] && echo "owner = \"${TF_VAR_owner}\""
  [ -n "${TF_VAR_pdl_sandbox:-}" ] && echo "pdl_sandbox = ${TF_VAR_pdl_sandbox}"
  true
} > "$OUT"

# The same variables must not also arrive through the environment, or Terraform would
# see them twice; the workflow scopes them to this step only. Report what was written
# without echoing the email address.
echo "wrote $OUT: $(grep -c '=' "$OUT") variable(s)"
